### ISSUE TITLE
Wrong link to clone respo

### ISSUE THREAD

**Issue by krewetka** [sulu-io/ExampleNewsBundle#7]
Hi!

In your installation instruction there is :

> git clone git@github.com:sulu-io/ExampleNewsBundle.git NewsBundle

I think there should be 

> https://github.com/sulu-io/ExampleNewsBundle.git NewsBundle

At least first one gives me error:

> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

and second one works :)

Would be great to add also small mention about 

>  app/console assets:install --symlink --relative 

somewhere here in installation instructions.

I know it's mentioned on blog ( I found it there) but earlier I just tried without it and had problem with missing symlinks. 

Also adding info in installation instructions about database schema update would be nice if someone just want's to try quicly example from git. I forgot about it ;)

> app/console doctrine:schema:update --force

**Comment by wachterjohannes** [comment]
thanks for the hint. also the symfony-standard is wrong it should be sulu-standard
