### ISSUE TITLE
Locale in url : error loading main.js

### ISSUE THREAD

**Issue by ahoul** [sulu-io/ExampleNewsBundle#9]
Hello, 

After login on admin nothing is displayed and there is an error in console :

"Error: Script error for: /bundles/news/dist/main.js"

URL loaded contains locale '.../en/bundles/news/dist/main.js'.

How can I fix it ?

thanks

**Comment by wachterjohannes** [comment]
do you run in production or development mode of symfony?

**Comment by ahoul** [comment]
I run in dev

**Comment by wachterjohannes** [comment]
this seems to be related to the upgrade issue. https://github.com/sulu/ExampleNewsBundle/issues/8

**Comment by wachterjohannes** [comment]
@ahoul in the current master i have updated to sulu/sulu 1.2 can you give me a hint if you still have problems?
